### PR TITLE
Create HOW_TO.md

### PR DESCRIPTION
**Pull request by lucasgonze**
Incorporate https://github.com/lucasgonze/hackersdmcaguide

### CODE REVIEW

**Comment by kemitchell** [comment]
This is certainly _a_ way to handle DMCA, but it prescribes a bit more than is necessary---as hackers might say, it's "opinionated".

I definitely think the site lacked a note that DMCA policies like DMCASimple only work if you _also_ follow the other requirements for safe harbor, like registering an agent with the Copyright Office. But I'm loathe to say that, for example, the DMCA requires disabling accounts after two complaints.

**Comment by lucasgonze** [comment]
Let's talk about goals and use cases.

My goal with this project was to enable developers to avoid hiring a lawyer for a task that is fairly mechanistic, because that is too slow, labor-intensive, and expensive for many projects. Being opinionated is an alternative. For example, disabling accounts after two complaints is a literal interpretation of the term "repeat" in "repeat infringer."

It would be helpful to my project to have a substantive conversation about the opinions I offered. I'd like to incorporate your thoughts in the recommendations.

**Comment by kemitchell** [comment]
@lucasgonze that's a good goal. DMCASimple makes a nice stepping stone along the way.

I suspect the opportunity here is to do some straightforward framing around when DMCA applies and who can use it. And from there making clear that's what's offered is an opinionated approach.

**Comment by kemitchell** [comment]
I've just pushed and published 07ba177edf4ca31583140fdc0b1f7b27d66127d2, which adds more information on the requirements for DMCA protection to https://dmcasimple.com/use. I think it would make a lot of sense to add sections on how to handle the different kinds of requests, and how to handle repeat infringers, to that page as it reads now.

@lucasgonze might you be interested in reworking your PR that way?

**Comment by lucasgonze** [comment]
> @lucasgonze might you be interested in reworking your PR that way?

This makes good sense to me. I will think about how to massage this MR into a form that would fit in /use.

**Comment by lucasgonze** [comment]
I added this content to use.html. I think it's an awkward fit there, but you are welcome to use it.

Other options:

1. Create a separate page
2. Add a link to https://github.com/lucasgonze/hackersdmcaguide

**Pull request closed without merging**
